SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS folder_items;
DROP TABLE IF EXISTS folders;
DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios (
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
UNIQUE KEY email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE folders (
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NOT NULL,
name VARCHAR(100) NOT NULL,
bio TEXT DEFAULT NULL,
coverUrl VARCHAR(255) DEFAULT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
KEY user_id_idx (user_id),
CONSTRAINT folders_ibfk_1 FOREIGN KEY (user_id) REFERENCES usuarios (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE folder_items (
id INT(11) NOT NULL AUTO_INCREMENT,
folder_id INT(11) NOT NULL,
item_id VARCHAR(100) NOT NULL,
image_url TEXT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
UNIQUE KEY unique_folder_item (folder_id,item_id),
CONSTRAINT folder_items_ibfk_1 FOREIGN KEY (folder_id) REFERENCES folders (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE favorites (
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NOT NULL,
item_id VARCHAR(100) NOT NULL,
image_url TEXT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
UNIQUE KEY unique_user_favorite (user_id,item_id),
CONSTRAINT favorites_ibfk_1 FOREIGN KEY (user_id) REFERENCES usuarios (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;